[package]
name = "shuvarie-highlight"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pulldown-cmark = { version = "0.13", default-features = false }
ratatui = { version = "0.30.2", default-features = false, features = ["std"] }
syntect = { version = "5.3", default-features = false, features = ["parsing", "default-syntaxes", "regex-fancy"] }
