[package]
name = "shuvarie-db"
description = "Blazingly fast AI coding TUI for chivalrous people (DB module)"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
base64.workspace = true
jiff.workspace = true
kdl.workspace = true
serde.workspace = true
serde_json.workspace = true
selune.workspace = true
sha2.workspace = true
shuvarie-config.workspace = true
shuvarie-llm.workspace = true
thiserror.workspace = true
toasty = { version = "0.11", features = ["turso", "jiff", "migration"] }
toasty-cli = "0.11"
toasty-driver-turso = { version = "0.11", features = ["fts"] }
tokio.workspace = true
turso = { version = "0.7", features = ["pure-rust-crypto"] }
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
uuid.workspace = true
