[package]
name = "shuvarie-db"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
jiff = "0.2"
serde.workspace = true
serde_json.workspace = true
selune.workspace = true
shuvarie-config.workspace = true
shuvarie-llm.workspace = true
thiserror.workspace = true
toasty = { version = "0.10", features = ["turso", "jiff", "migration"] }
toasty-cli = "0.10"
toasty-driver-turso = "0.10"
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
uuid.workspace = true
