pub mod agents;
pub mod command;
pub mod config;
pub mod connections;
pub mod context;
pub mod core_task;
pub mod embeddings;
mod error;
pub mod event;
pub mod session;
pub mod tools;

pub use command::Command;
pub use config::{Config, EmbeddingConfig, UiPrefs};
pub use connections::{Connections, ProviderConfig};
pub use core_task::run;
pub use error::{CoreError, Result};
pub use event::Event;
pub use session::Session;
pub use shuvarie_catalog::{ModelInfo, Provider};
pub use shuvarie_db::{MsgRole, SearchHit, SearchSource, SessionSummary};
pub use shuvarie_llm::{ChatMsg, Role};
