name: Lint & Test

on:
  #push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true
    - uses: dtolnay/rust-toolchain@stable
    - name: Lint
      run: cargo clippy

    - name: Run tests
      run: cargo test
