[package]
name = "shuvarie-llm"
description = "AI coding TUI for chivalrous people (LLM module)"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
futures-core = "0.3"
futures-util.workspace = true
http.workspace = true
reqwest.workspace = true
# Do NOT include `rig`. It has too many implicit dependencies.
rig-agent = "0.42"
rig-core = "0.42"
serde.workspace = true
serde_json.workspace = true
selune.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
rig-agent = { version = "0.42", features = ["test-utils"] }
tokio = { workspace = true, features = ["time"] }
